#!/usr/bin/ruby

require 'json'
require 'net/http'
require 'uri'

var_name = 'GOOGLE_CHAT_NOTIFICATION_WEBHOOK'
if ENV.has_key?(var_name) && !ENV[var_name].empty?
  url = URI(ENV[var_name])
  Net::HTTP.post(url, {text: ARGV[0]}.to_json, {'Content-Type': 'application/json'})
else
  raise "Environment variable '#{var_name}' missing."
end
